//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public   class DanhMucCha
    {
    
    
        public int Id { get; set; }
        public string TenDM { get; set; }
    
        public   ICollection<DanhMuc> DanhMucs { get; set; }
    }
}
