//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public   class DanhMuc
    {
       
    
    
        public int Id { get; set; }
        public string TenDanhMuc { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
        public int IdDanhMucCha { get; set; }
     
        public   ICollection<BaiViet> BaiViets { get; set; }
        
        public   DanhMucCha DanhMucCha { get; set; }
    }
}
