//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class DanhGia
    {
        public int Id { get; set; }
        public string NoiDung { get; set; }
        public int IdTinTuc { get; set; }
        public int IdTaiKhoan { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
        public bool TrangThai { get; set; }
    
        public   BaiViet? BaiViet { get; set; }
        public int BaiVietId { get; set;}
       public string UserName { get; set; }
    }
}
