//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public   class TaiKhoan
    {
        
    
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public TrangThai TrangThai { get; set; }
        public bool Quyen { get; set; }
        public System.DateTime NgaySinh { get; set; }
     
        public   ICollection<BaiViet>? BaiViets { get; set; }
 
        public   ICollection<DanhGia>? DanhGias { get; set; }
    }

    public enum TrangThai
    {
        ChoDuyet = 0,
        Duyet = 1,
        Block =2
    }
}
