// <auto-generated />
using System;
using Food.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Food.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230525195402_now3")]
    partial class now3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReviewFood.Models.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("ReviewFood.Models.BaiViet_DanhMuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinTuc", "MaDanhMuc");

                    b.ToTable("BaiViet_DanhMuc");
                });

            modelBuilder.Entity("ReviewFood.Models.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int>("BaiVietId")
                        .HasColumnType("int");

                    b.Property<int>("IdTinTuc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "IdTaiKhoan", "BaiVietId");

                    b.HasIndex("BaiVietId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("ReviewFood.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDanhMucCha")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDanhMuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMucCha");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("ReviewFood.Models.DanhMucCha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucChas");
                });

            modelBuilder.Entity("ReviewFood.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Quyen")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("ReviewFood.Models.BaiViet", b =>
                {
                    b.HasOne("ReviewFood.Models.DanhMuc", "DanhMuc")
                        .WithMany("BaiViets")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewFood.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("BaiViets")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ReviewFood.Models.DanhGia", b =>
                {
                    b.HasOne("ReviewFood.Models.BaiViet", "BaiViet")
                        .WithMany("DanhGias")
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewFood.Models.TaiKhoan", null)
                        .WithMany("DanhGias")
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("BaiViet");
                });

            modelBuilder.Entity("ReviewFood.Models.DanhMuc", b =>
                {
                    b.HasOne("ReviewFood.Models.DanhMucCha", "DanhMucCha")
                        .WithMany("DanhMucs")
                        .HasForeignKey("IdDanhMucCha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("ReviewFood.Models.BaiViet", b =>
                {
                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("ReviewFood.Models.DanhMuc", b =>
                {
                    b.Navigation("BaiViets");
                });

            modelBuilder.Entity("ReviewFood.Models.DanhMucCha", b =>
                {
                    b.Navigation("DanhMucs");
                });

            modelBuilder.Entity("ReviewFood.Models.TaiKhoan", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("DanhGias");
                });
#pragma warning restore 612, 618
        }
    }
}
